version: '3'

services:
  db:
    image: postgres
  devcon:
    image: pasmo/devcon_api:latest
    build: .
    container_name: devcon_api
    command: ./scripts.sh
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - IN_DOCKER=1
