version: '3'

services:
  db:
    image: postgres
  devcon_api:
    image: pasmo/restfull_devcon_api:latest
    build: .
    container_name: restful_devcon_api
    command: ./scripts.sh
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - IN_DOCKER=1
